name: Notify on Commit

on:
  push:
    branches:
      - main  # Ganti dengan nama branch yang sesuai

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Send Notification
        run: |
          curl -s -X POST \
            https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d "chat_id=$TELEGRAM_CHAT_ID" \
            -d "text=🚀 New commit pushed to $GITHUB_REPOSITORY!\n\n$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/$GITHUB_SHA" \
            -H "Content-Type: application/json"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          
