name: Update README

on:
  schedule:
    - cron: '*/0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: FebriCahyaa/FebriCahyaa@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
